### ISSUE TITLE
make images for games cache

### ISSUE THREAD

**Issue by RUGAY** [AmeerDotEXE/roblokis#1]
hello I looked at the lighthouse for the roblox games page and it said (at the time of writing this I'm not gonna do another lighthouse test also it may be wrong) to make the images webp or another (modern) format.

(also I'm gonna make a bunch of ideas in issues so I'm not spamming)

**Comment by AmeerDotEXE** [comment]
can you explain this in more details i didn't understand it

you can make suggestions here but i would recommend you use discord
its up to you

**Comment by RUGAY** [comment]
basically cache the images in the browser

**Comment by AmeerDotEXE** [comment]
that a worse explanation
like what image would it save?
in what site?
for what propose?
