### ISSUE TITLE
badge text overlap with borders

### ISSUE THREAD

**Issue by RUGAY** [AmeerDotEXE/roblokis#2]
idk how to put it in words so I'm gonna show it to you
![Screen Shot 2022-01-18 at 11 21 11 AM](https://user-images.githubusercontent.com/66430716/149986919-e071d803-859e-44d6-87c7-1e6c089b24dd.png)

**Comment by RUGAY** [comment]
also why does this happen
![Screen Shot 2022-01-18 at 11 35 51 AM](https://user-images.githubusercontent.com/66430716/149989062-c5cc6dd1-46d8-42b8-80be-9038ff42be32.png)
there's like a max amount of badges

**Comment by AmeerDotEXE** [comment]
that happens when you hav other extensions with roblokis
added support for BTRoblox, RoPro, RoGold and Roblox+
in version 3.0.1
thanks for your report
