### ISSUE TITLE
better support with other roblox extensions + better server logic

### ISSUE THREAD

**Issue by RUGAY** [AmeerDotEXE/roblokis#3]
i recently got ropro so this wierd thing happens

https://user-images.githubusercontent.com/66430716/149987580-4098c13e-dee3-4556-ad29-9da30be7afc4.mov

(uncroppped)

https://user-images.githubusercontent.com/66430716/149987770-f95abfaf-72ee-4d07-8515-773299812b2d.mov

feels weird not being like this
![Screen Shot 2022-01-18 at 11 28 43 AM](https://user-images.githubusercontent.com/66430716/149988131-34b0da28-2fa2-4a46-8c77-f6196a092f60.png)
like the text box on top of the server location

**Comment by AmeerDotEXE** [comment]
added support for BTRoblox, RoPro, RoGold and Roblox+
in version 3.0.1
thanks for your report

**Comment by cantdecidemyname** [comment]
![Image](https://github.com/user-attachments/assets/cf2d604d-a9ce-4c0d-8933-97332e253238)
is this normal, after turning on the theme and styles settings it seems to do that, i dont wanna turn it off now cus it looks really good. i dont know if is my other roblox extensions causing this to happen.
